// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfmU8XEqXpa_NL3NfC-3vORSMceHUUi3c',
    appId: '1:799434034952:web:dd0a7b9a0ea63bd812e6bd',
    messagingSenderId: '799434034952',
    projectId: 'corte-online',
    authDomain: 'corte-online.firebaseapp.com',
    storageBucket: 'corte-online.appspot.com',
    measurementId: 'G-4GVEM5ZBS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAof1g2jP1Ax8276iLk2KG3UnHJVl30tBk',
    appId: '1:799434034952:android:7993a063e762391e12e6bd',
    messagingSenderId: '799434034952',
    projectId: 'corte-online',
    storageBucket: 'corte-online.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaPMZVdVNwsQerwqvbNGiBAYO68KO7E7E',
    appId: '1:799434034952:ios:f32477a4fb709dd612e6bd',
    messagingSenderId: '799434034952',
    projectId: 'corte-online',
    storageBucket: 'corte-online.appspot.com',
    iosBundleId: 'br.com.corteonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaPMZVdVNwsQerwqvbNGiBAYO68KO7E7E',
    appId: '1:799434034952:ios:f32477a4fb709dd612e6bd',
    messagingSenderId: '799434034952',
    projectId: 'corte-online',
    storageBucket: 'corte-online.appspot.com',
    iosBundleId: 'br.com.corteonline',
  );
}
