// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgdDKKm0zGF1eXiInkBEqfHWdUJrT-gOM',
    appId: '1:173798567063:web:97c51f72f18fe392f10dd2',
    messagingSenderId: '173798567063',
    projectId: 'corte-certo-84692',
    authDomain: 'corte-certo-84692.firebaseapp.com',
    storageBucket: 'corte-certo-84692.appspot.com',
    measurementId: 'G-2LRDMBPDDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe35X9XoHCDvPmz0etxY6AIa-8FReKmps',
    appId: '1:173798567063:android:e4ba509ae96690e1f10dd2',
    messagingSenderId: '173798567063',
    projectId: 'corte-certo-84692',
    storageBucket: 'corte-certo-84692.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeY3PyDoEYeDIf7xSAA4uyccPYPdh7quk',
    appId: '1:173798567063:ios:c8e9032d80d00965f10dd2',
    messagingSenderId: '173798567063',
    projectId: 'corte-certo-84692',
    storageBucket: 'corte-certo-84692.appspot.com',
    iosClientId: '173798567063-dokkieottoi1m3nd9chg03neq1issb0h.apps.googleusercontent.com',
    iosBundleId: 'br.com.cortecerto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeY3PyDoEYeDIf7xSAA4uyccPYPdh7quk',
    appId: '1:173798567063:ios:c8e9032d80d00965f10dd2',
    messagingSenderId: '173798567063',
    projectId: 'corte-certo-84692',
    storageBucket: 'corte-certo-84692.appspot.com',
    iosClientId: '173798567063-dokkieottoi1m3nd9chg03neq1issb0h.apps.googleusercontent.com',
    iosBundleId: 'br.com.cortecerto',
  );
}
